//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo140421.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public ChamCong()
        {
            this.LoaiChams = new HashSet<LoaiCham>();
        }
    
        public int MaCC { get; set; }
        public Nullable<System.DateTime> NgayCham { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaNV_CC { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<LoaiCham> LoaiChams { get; set; }
    }
}
