//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo140421.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucDanh
    {
        public ChucDanh()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaCD { get; set; }
        public string TenCD { get; set; }
        public Nullable<double> LuongCB { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
