//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo140421.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Phai { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<double> DoanhSo { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual LoaiKH LoaiKH { get; set; }
    }
}
