//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo140421.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiCham
    {
        public LoaiCham()
        {
            this.ChamCongs = new HashSet<ChamCong>();
        }
    
        public int MaLC { get; set; }
        public string TenLC { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
    }
}
