//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo140421.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.ChamCongs = new HashSet<ChamCong>();
            this.ChamCongs1 = new HashSet<ChamCong>();
            this.HoaDons = new HashSet<HoaDon>();
            this.Luongs = new HashSet<Luong>();
            this.NhanVien1 = new HashSet<NhanVien>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public int MaNV { get; set; }
        public string Ho { get; set; }
        public string TenLot { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Phai { get; set; }
        public string CCCD { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayBDLam { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaCH { get; set; }
        public Nullable<int> MaNV_QL { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
        public virtual ICollection<ChamCong> ChamCongs1 { get; set; }
        public virtual ChucDanh ChucDanh { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<Luong> Luongs { get; set; }
        public virtual ICollection<NhanVien> NhanVien1 { get; set; }
        public virtual NhanVien NhanVien2 { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
