//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo140421.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CT_DonHang = new HashSet<CT_DonHang>();
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
            this.CT_HoaDonNhap = new HashSet<CT_HoaDonNhap>();
            this.SP_PhanBo = new HashSet<SP_PhanBo>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int MaMau { get; set; }
        public int MaSize { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual ICollection<CT_HoaDonNhap> CT_HoaDonNhap { get; set; }
        public virtual KhoHang KhoHang { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual Size Size { get; set; }
        public virtual ICollection<SP_PhanBo> SP_PhanBo { get; set; }
    }
}
